### ISSUE TITLE
Unity Package Manager Error on Opening Project

### ISSUE THREAD

**Issue by bbacle** [gtoto007/Learning-alphabet-letters-game#1]
![Error](https://user-images.githubusercontent.com/5198599/155623785-9c08c148-eeaa-4ae7-b3c2-0bd5ef89dc24.PNG)
And then when I attempt to open the file, I get dozens of coding errors.
![Unity Errors](https://user-images.githubusercontent.com/5198599/155624277-e5829a0e-e3a7-4870-8a1a-b8b744efb362.PNG)

**Comment by gtoto007** [comment]
The unity project uses git software to install some dependencies. So you need to install git before opening the unity project.

**Comment by bbacle** [comment]
I have installed git, but I am getting the same errors. Can't you just negate the git requirement?

**Comment by gtoto007** [comment]
No because the package management unity works with git. Also, if you want to learn how to develop I recommend that you learn how to use git.

Anyway, after installing Git you need to restart your PC. Open your terminal and run the git command to verify that you have installed git correctly.

If you still have problems, search on google "no git executable" to have more information to resolve your problem.

**Comment by bbacle** [comment]
OK...figured out how to get Git on my computer. I had installed the Git desktop, which apparently wasn't enough (which is strange). Now my question is this: Would a build of this require Git to be installed on the computer in order for it to run?

**Comment by bbacle** [comment]
Also I noticed that when you get to z & you get all of them the game starts over. Mine went on to the next character in the font, which was a curly brace {, & then on til it got to little boxes.

**Comment by gtoto007** [comment]
> OK...figured out how to get Git on my computer. I had installed the Git desktop, which apparently wasn't enough (which is strange). Now my question is this: Would a build of this require Git to be installed on the computer in order for it to run?

No, when you work with unity, git is used only to install the project dependencies. You can check unity documentation for more information: https://docs.unity3d.com/2019.3/Documentation/Manual/upm-ui-giturl.html

**Comment by gtoto007** [comment]
> Also I noticed that when you get to z & you get all of them the game starts over. Mine went on to the next character in the font, which was a curly brace {, & then on til it got to little boxes.

I didn’t understand. Anyway you have to open a new issue to explain your problem. Also you must know that this project is just a demonstration of how 
 unity atoms plugin works. It is not a game complete but it’s a good starting point  for building your own game.
